services:
  - type: web
    runtime: node
    name: gestao-pallets
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
